<?php

/**
 * Created by PhpStorm.
 * User: peterzolintakis
 * Date: 4/9/17
 * Time: 6:45 PM
 */

use PHPUnit\Framework\TestCase;


class GetAbstractTest extends TestCase
{

    public function testGetAbstract(){
        $abstract = GetAbstractDriver::getAbstract("On the Feasibility of Breast Cancer Imaging Systems at Millimeter-Waves Frequencies", "Simona Di Meo Pedro Fidel Espín-López Andrea Martellosio Marco Pasian  Giulia Matrone");
        $correctAbstract = "Medical imaging currently relies on several techniques, including X-rays, magnetic resonance, and echography. However, these techniques exhibit drawbacks, and alternative approaches are required. Microwave imaging has been proposed as a possible solution, especially for breast cancer imaging. However, most of these systems work with a central frequency of a few gigahertz, and this leads to a suboptimum resolution, which can jeopardize the image quality. Millimeter waves can provide superior resolutions, at the cost of a lower penetration depth within the breast tissue. In addition, a significant fraction of the power generated by a mm-wave imaging system would be reflected back from the skin. For these reasons, and also considering that mm-wave transmitters and receivers have been historically outperformed by microwave counterparts in terms of available power and sensitivity, mm-wave imaging has not been considered a possible solution. This paper contributes to demonstrate a paradigm shift toward the possible use of mm-waves for breast cancer imaging of targets a few centimeter below the skin, a useful penetration depth for several cases. All key points are addressed using analytical, full-wave, and multiphysics simulations, including the system architecture (linear and conformal), the safety aspects (power density, specific absorption rate, and temperature increase), and the use of realistic breast models derived from ex vivo measurements.";
        $this->assertEquals($abstract, $correctAbstract);
    }

}